name: 'C++ CI Windows'

on:
  push:
    branches:
      - main
      - lab-1

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
        - name
